INSERT INTO USERS (ID, VERSION, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (0, 0, 'admin', 'admin@gmail.com', 'admin', 'ADMIN');

INSERT INTO ISSUES (VERSION, USERID, RECORD_DATE, DESCRIPTION, LOCATION, STATUS) VALUES (0, 0, CURRENT_TIMESTAMP(), 'Valami hiba', 'PC9', 'OPEN');

INSERT INTO MESSAGES (VERSION, ISSUEID, MESSAGE, MESSAGE_DATE) VALUES (0, 0, 'Valami uzenet', CURRENT_DATE());